/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Users.*;
import Utiliarios.Tools;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LucasPc
 */
public class AdmPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdmPanel
     */
    public AdmPanel() {
        initComponents();
    }
    Clinica _clinica = new Clinica();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code, if you modify this code you will die!
     * The end is comming, so please, do not modify this code, it has the power
     * to save the world! The content of this method is always regenerated by
     * God, ALWAYS!
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jConsultaDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtCpfCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtMarcarConsulta = new javax.swing.JButton();
        cbSetRegMed = new javax.swing.JComboBox();
        jLabel = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jClienteDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txtCpfCliente1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jBtAddCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTelCliente = new javax.swing.JTextField();
        jDentistaDialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txtCpfMedico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNomeMedico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRegistroMedico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JCBEspecialidade = new javax.swing.JComboBox();
        jBAddDentista = new javax.swing.JButton();
        jClienteDialog1 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        txtCpfCliente2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNomeCliente1 = new javax.swing.JTextField();
        jBtAddCliente1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTelCliente1 = new javax.swing.JTextField();
        jDialog1 = new javax.swing.JDialog();
        jBSavarEdicao = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jCBSelPropriedade = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jPopupMenu = new javax.swing.JPopupMenu();
        popMEditar = new javax.swing.JMenuItem();
        popMExcluir = new javax.swing.JMenuItem();
        jPopupMenuConsulta = new javax.swing.JPopupMenu();
        popMEditarConsulta = new javax.swing.JMenuItem();
        popMExcluirConsulta = new javax.swing.JMenuItem();
        jCBDia = new javax.swing.JComboBox();
        jCBMes = new javax.swing.JComboBox();
        jCBAno = new javax.swing.JComboBox();
        txtEditCliente = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ConsultasPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jBtAddConsulta = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        ClientesPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jBtAddNCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        GerenciaPanel = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jbAddDentistadg = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFuncionario = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDentista = new javax.swing.JTable();

        jConsultaDialog.setTitle("Nova Consulta");
        jConsultaDialog.setMinimumSize(new java.awt.Dimension(334, 194));
        jConsultaDialog.setResizable(false);
        jConsultaDialog.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jConsultaDialogComponentShown(evt);
            }
        });

        jLabel1.setText("CPF");

        jLabel2.setText("Data");

        jBtMarcarConsulta.setText("Adicionar");
        jBtMarcarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtMarcarConsultaActionPerformed(evt);
            }
        });

        cbSetRegMed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel.setText("Médico");

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jConsultaDialogLayout = new javax.swing.GroupLayout(jConsultaDialog.getContentPane());
        jConsultaDialog.getContentPane().setLayout(jConsultaDialogLayout);
        jConsultaDialogLayout.setHorizontalGroup(
            jConsultaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConsultaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jConsultaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtMarcarConsulta)
                    .addGroup(jConsultaDialogLayout.createSequentialGroup()
                        .addGroup(jConsultaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jConsultaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSetRegMed, 0, 182, Short.MAX_VALUE)
                            .addComponent(txtCpfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jConsultaDialogLayout.setVerticalGroup(
            jConsultaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConsultaDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jConsultaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jConsultaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSetRegMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jConsultaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jBtMarcarConsulta)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jConsultaDialog.getAccessibleContext().setAccessibleName("Cinsu");

        jClienteDialog.setTitle("Novo Cliente");
        jClienteDialog.setMinimumSize(new java.awt.Dimension(334, 189));
        jClienteDialog.setResizable(false);

        jLabel3.setText("CPF");

        jLabel4.setText("Nome");

        jBtAddCliente.setText("Adicionar");
        jBtAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone");

        javax.swing.GroupLayout jClienteDialogLayout = new javax.swing.GroupLayout(jClienteDialog.getContentPane());
        jClienteDialog.getContentPane().setLayout(jClienteDialogLayout);
        jClienteDialogLayout.setHorizontalGroup(
            jClienteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClienteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jClienteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClienteDialogLayout.createSequentialGroup()
                        .addGroup(jClienteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jClienteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpfCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBtAddCliente))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jClienteDialogLayout.setVerticalGroup(
            jClienteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClienteDialogLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jClienteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCpfCliente1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jClienteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jClienteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtAddCliente)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jDentistaDialog.setTitle("Novo Dentista");
        jDentistaDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDentistaDialog.setMinimumSize(new java.awt.Dimension(334, 208));
        jDentistaDialog.setResizable(false);

        jLabel8.setText("CPF");

        jLabel9.setText("Nome");

        jLabel10.setText("Registro");

        jLabel11.setText("Especialidade");

        jBAddDentista.setText("Adicionar");
        jBAddDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddDentistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDentistaDialogLayout = new javax.swing.GroupLayout(jDentistaDialog.getContentPane());
        jDentistaDialog.getContentPane().setLayout(jDentistaDialogLayout);
        jDentistaDialogLayout.setHorizontalGroup(
            jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDentistaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDentistaDialogLayout.createSequentialGroup()
                        .addGroup(jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JCBEspecialidade, 0, 160, Short.MAX_VALUE)
                            .addComponent(txtNomeMedico)
                            .addComponent(txtCpfMedico)
                            .addComponent(txtRegistroMedico)))
                    .addComponent(jBAddDentista))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jDentistaDialogLayout.setVerticalGroup(
            jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDentistaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCpfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRegistroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDentistaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JCBEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAddDentista)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jClienteDialog1.setTitle("Novo Cliente");
        jClienteDialog1.setMinimumSize(new java.awt.Dimension(334, 189));
        jClienteDialog1.setResizable(false);

        jLabel6.setText("CPF");

        jLabel7.setText("Nome");

        jBtAddCliente1.setText("Adicionar");
        jBtAddCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddCliente1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Telefone");

        javax.swing.GroupLayout jClienteDialog1Layout = new javax.swing.GroupLayout(jClienteDialog1.getContentPane());
        jClienteDialog1.getContentPane().setLayout(jClienteDialog1Layout);
        jClienteDialog1Layout.setHorizontalGroup(
            jClienteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClienteDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jClienteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClienteDialog1Layout.createSequentialGroup()
                        .addGroup(jClienteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(50, 50, 50)
                        .addGroup(jClienteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpfCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBtAddCliente1))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jClienteDialog1Layout.setVerticalGroup(
            jClienteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClienteDialog1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jClienteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCpfCliente2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jClienteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jClienteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTelCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtAddCliente1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jDialog1.setTitle("Editar Cliente");
        jDialog1.setBounds(new java.awt.Rectangle(443, 4, 4, 4));
        jDialog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog1.setMinimumSize(new java.awt.Dimension(314, 128));
        jDialog1.setResizable(false);
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialog1WindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialog1WindowClosing(evt);
            }
        });

        jBSavarEdicao.setText("Salvar");
        jBSavarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSavarEdicaoActionPerformed(evt);
            }
        });

        jCBSelPropriedade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBSelPropriedade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSelPropriedadeActionPerformed(evt);
            }
        });

        jLabel14.setText("Editar");

        jToolBar2.setRollover(true);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCBSelPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jBSavarEdicao)))
                .addGap(19, 19, 19))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBSelPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSavarEdicao)))
        );

        jPopupMenu.setAlignmentX(2.0F);
        jPopupMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPopupMenu.setBounds(0, 0, 200, 200);

        popMEditar.setText("Editar");
        popMEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popMEditarActionPerformed(evt);
            }
        });
        jPopupMenu.add(popMEditar);

        popMExcluir.setText("Excluir");
        popMExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popMExcluirActionPerformed(evt);
            }
        });
        jPopupMenu.add(popMExcluir);

        jPopupMenuConsulta.setAlignmentX(2.0F);
        jPopupMenuConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPopupMenu.setBounds(0, 0, 200, 200);

        popMEditarConsulta.setText("Editar");
        popMEditarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popMEditarConsultaActionPerformed(evt);
            }
        });
        jPopupMenuConsulta.add(popMEditarConsulta);

        popMExcluirConsulta.setText("Excluir");
        popMExcluirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popMExcluirConsultaActionPerformed(evt);
            }
        });
        jPopupMenuConsulta.add(popMExcluirConsulta);

        jCBDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11", " " }));

        jCBMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCBAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtEditCliente.setMinimumSize(new java.awt.Dimension(191, 23));
        txtEditCliente.setPreferredSize(new java.awt.Dimension(191, 23));

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMinimumSize(new java.awt.Dimension(462, 564));
        setPreferredSize(new java.awt.Dimension(462, 564));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTabbedPane1.setName("tbCliente"); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(442, 542));

        ConsultasPanel.setBackground(new java.awt.Color(255, 255, 255));

        jBtAddConsulta.setText("Adicionar Consulta");
        jBtAddConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddConsultaActionPerformed(evt);
            }
        });

        jButton4.setText("Pesquisar");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbConsulta.setToolTipText("");
        tbConsulta.setComponentPopupMenu(jPopupMenu);
        tbConsulta.setName("tbConsulta"); // NOI18N
        jScrollPane4.setViewportView(tbConsulta);

        javax.swing.GroupLayout ConsultasPanelLayout = new javax.swing.GroupLayout(ConsultasPanel);
        ConsultasPanel.setLayout(ConsultasPanelLayout);
        ConsultasPanelLayout.setHorizontalGroup(
            ConsultasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(ConsultasPanelLayout.createSequentialGroup()
                        .addComponent(jBtAddConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        ConsultasPanelLayout.setVerticalGroup(
            ConsultasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConsultasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addComponent(jBtAddConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultas", ConsultasPanel);

        ClientesPanel.setBackground(new java.awt.Color(255, 255, 255));

        jBtAddNCliente.setText("Adicionar Cliente");
        jBtAddNCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddNClienteActionPerformed(evt);
            }
        });

        tbCliente.setAutoCreateRowSorter(true);
        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCliente.setComponentPopupMenu(jPopupMenu);
        tbCliente.setGridColor(new java.awt.Color(51, 255, 51));
        tbCliente.setName("tbCliente"); // NOI18N
        tbCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tbCliente);

        javax.swing.GroupLayout ClientesPanelLayout = new javax.swing.GroupLayout(ClientesPanel);
        ClientesPanel.setLayout(ClientesPanelLayout);
        ClientesPanelLayout.setHorizontalGroup(
            ClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(ClientesPanelLayout.createSequentialGroup()
                        .addComponent(jBtAddNCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                .addContainerGap())
        );
        ClientesPanelLayout.setVerticalGroup(
            ClientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtAddNCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", ClientesPanel);

        GerenciaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jbAddDentistadg.setText("Adicionar Dentista");
        jbAddDentistadg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddDentistadgActionPerformed(evt);
            }
        });

        jButton5.setText("Adicionar Funcionario");

        tbFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbFuncionario);

        tbDentista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDentista.setName("tbDentista"); // NOI18N
        jScrollPane3.setViewportView(tbDentista);

        javax.swing.GroupLayout GerenciaPanelLayout = new javax.swing.GroupLayout(GerenciaPanel);
        GerenciaPanel.setLayout(GerenciaPanelLayout);
        GerenciaPanelLayout.setHorizontalGroup(
            GerenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GerenciaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GerenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GerenciaPanelLayout.createSequentialGroup()
                        .addGroup(GerenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbAddDentistadg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GerenciaPanelLayout.setVerticalGroup(
            GerenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerenciaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAddDentistadg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gerenciar", GerenciaPanel);

        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    //Os proximos 3 eventos iniciam a adição dos dados no banco
    //1
    private void jBtMarcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtMarcarConsultaActionPerformed
        Calendar d = Calendar.getInstance();
        //int i = (int) jCBAno.getSelectedItem();
        int selectedDia = jCBDia.getSelectedIndex();
        int selectedMes = jCBMes.getSelectedIndex();
        int selectedAno = (int) jCBAno.getSelectedItem();
        d.set(selectedAno, selectedMes, (selectedDia + 1));
        //Pega o cpf atraves do indice
        int reg = cbSetRegMed.getSelectedIndex();
        /*bug aqui **************** ***** 
         ->->->->->  Ouvindo a 11° de Haydn
         bug abaixo
         */
        if (_clinica.MarcarConsulta(new Consulta(txtCpfCliente.getText(), _clinica.Medicos.get(reg).getRegistro_M(),
                d))) {
            this.jConsultaDialog.dispose();;
            Tools.showMessage(1);
        } else {
            Tools.showMessage(2);
        }
        att();
    }//GEN-LAST:event_jBtMarcarConsultaActionPerformed
    //2
    private void jBtAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddClienteActionPerformed
        boolean AddCliente;
        if (_clinica.AddCliente(new Cliente(txtCpfCliente1.getText(), txtNomeCliente.getText(), txtTelCliente.getText()))) {
            this.jClienteDialog.dispose();;
            Tools.showMessage(1);
        } else {
            Tools.showMessage(2);
        }
        att();
    }//GEN-LAST:event_jBtAddClienteActionPerformed
    //3
    private void jBAddDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddDentistaActionPerformed
        int esp = JCBEspecialidade.getSelectedIndex();
        esp++;
        if (_clinica.AddMedico(new Medico(txtCpfMedico.getText(), txtNomeMedico.getText(),
                txtRegistroMedico.getText(), esp))) {
            this.jDentistaDialog.dispose();;
            Tools.showMessage(1);
        } else {
            Tools.showMessage(2);
        }
        att();
    }//GEN-LAST:event_jBAddDentistaActionPerformed
    public void attTableCliente() {
        //Atualiza a tabela Cliente;
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(Tools.colunasCliente);
        _clinica.Clientes = _clinica.MostrarClientes();
        for (Cliente c : _clinica.Clientes) {
            model.addRow(new Object[]{c.getCpf(), c.getNome(), c.getTelefone()});
        }
        this.tbCliente.setModel(model);
        this.tbCliente.setFillsViewportHeight(true);
    }

    private void attTableDentista() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(Tools.colunasMedico);
        _clinica.Medicos = _clinica.MostrarMedicos();
        for (Medico m : _clinica.Medicos) {
            model.addRow(new Object[]{m.getRegistro_M(), m.getNome_M(), m.getCpf_M(), m.getStrEspecialidade()});
        }
        this.tbDentista.setModel(model);
        this.tbDentista.setFillsViewportHeight(true);

    }

    private void attTableConsulta() {
        //A mesma coisa...
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(Tools.colunasConsulta);
        SimpleDateFormat formataData = new SimpleDateFormat("dd-MM-yyyy");
        _clinica.Consultas = _clinica.MostrarConsultas();
        for (Consulta cs : _clinica.Consultas) {
            model.addRow(new Object[]{cs.getIdConsulta(), cs.getCpfCliente(),
                " " + cs.dadosMedico.getRegistro_M() + " (" + cs.dadosMedico.getNome_M() + ")",
                formataData.format(cs.getData().getTime())});
        }
        this.tbConsulta.setModel(model);
        this.tbConsulta.setFillsViewportHeight(true);
    }

    void att() {
        /*Atualiza tudo de uma vez, e seta os modelos dos ComboBoxes. 
         ... ... ... ... ...
         */
        attTableCliente();
        attTableConsulta();
        attTableDentista();
        this.JCBEspecialidade.setModel(Tools.getEspModel());
        this.cbSetRegMed.setModel(Tools.getMedEspModel());
    }

    //4. Abre jDialogs para cadastro
    private void jBtAddConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddConsultaActionPerformed
        this.jConsultaDialog.setVisible(true);
    }//GEN-LAST:event_jBtAddConsultaActionPerformed

    private void jBtAddNClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddNClienteActionPerformed
        this.jClienteDialog.setVisible(true);
    }//GEN-LAST:event_jBtAddNClienteActionPerformed


    private void jbAddDentistadgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddDentistadgActionPerformed
        this.jDentistaDialog.setVisible(true);
    }//GEN-LAST:event_jbAddDentistadgActionPerformed

    private void jBtAddCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddCliente1ActionPerformed

    }//GEN-LAST:event_jBtAddCliente1ActionPerformed

    /*
    private void popMEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMEditarActionPerformed
        int selectedColumn = this.tbCliente.getSelectedColumn();
     if (selectedColumn == -1) {
     JOptionPane message = new JOptionPane();
     JOptionPane.showMessageDialog(this,
     "Nenhuma coluna selecionada!",
     "Erro",
     JOptionPane.WARNING_MESSAGE);
     } else {
     this.jDialog1.setVisible(true);
     this.txtEditCliente.setText("");
     this.jCBClientePropriedade.setSelectedIndex(selectedColumn);
     }
    }//GEN-LAST:event_popMEditarActionPerformed
    */
    /*jMenuPopUp das tabelas [Edição]. Dependendo em que tabela isto for chamado
     o modelo do ComboBox será diferente
     */
    private void popMEditarActionPerformed(java.awt.event.ActionEvent evt) {
        JTable table = (JTable) this.jPopupMenu.getInvoker();
        String name = table.getName();
        DefaultComboBoxModel model = null;
        int selectedColumn = table.getSelectedColumn();
        if (selectedColumn == -1) {
            JOptionPane.showMessageDialog(this,
                    "Nenhuma coluna selecionada!",
                    "Erro",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            switch (name) {
                case "tbConsulta":
                    model = new DefaultComboBoxModel(Tools.colunasConsulta);
                    break;
                case "tbCliente":
                    model = new DefaultComboBoxModel(Tools.colunasCliente);
                    break;
                case "tbDentista":
                    model = new DefaultComboBoxModel(Tools.colunasMedico);
                    break;
                case "tbFuncionario":
                    model = new DefaultComboBoxModel(Tools.colunasFuncionario);
                    break;
            }
            this.jDialog1.setVisible(true);
            this.txtEditCliente.setText("");
            this.jCBSelPropriedade.setModel(model);
            this.jCBSelPropriedade.setSelectedIndex(selectedColumn);
        }
    }

    /*
    private void popMExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMExcluirActionPerformed
        String selectedCpf = (String) this.tbCliente.getValueAt(this.tbCliente.getSelectedRow(), 0);
     if (this.tbCliente.getSelectedRow() != -1) {
     int n = JOptionPane.showConfirmDialog(
     this,
     "Deseja excluir o item selecionado?",
     "Excluir",
     JOptionPane.YES_NO_OPTION);
     if (n == 0) {
     _clinica.ExcluirCliente(selectedCpf);
     att();
     }
     }
    }//GEN-LAST:event_popMExcluirActionPerformed
   */
    //PopUp Exclusao, bem simples. Sem comentarios
    private void popMExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        JTable table = (JTable) this.jPopupMenu.getInvoker();
        if (table.getSelectedRow() != -1) {
            int n = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja excluir o item selecionado?",
                    "Excluir",
                    JOptionPane.YES_NO_OPTION);
            if (n == 0) {
                String name = table.getName();
                String valueAt = table.getValueAt(table.getSelectedRow(), 0).toString();
                switch (name) {
                    case "tbConsulta":
                        _clinica.ExcluirConsulta(valueAt);
                        break;
                    case "tbCliente":
                        _clinica.ExcluirCliente(valueAt);
                        break;
                    case "tbDentista":
                        _clinica.ExcluirDentista(valueAt);
                }
                att();
            }
        }

    }

    private void popMEditarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMEditarConsultaActionPerformed
        Component invoker = this.jPopupMenuConsulta.getInvoker();
        JTable table = (JTable) this.jPopupMenuConsulta.getInvoker();
        String name = table.getName();
        int selectedColumn = table.getSelectedColumn();
        int selectedRow = table.getSelectedRow();
    }//GEN-LAST:event_popMEditarConsultaActionPerformed

    private void popMExcluirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMExcluirConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popMExcluirConsultaActionPerformed

    private void jDialog1WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowClosing
        att();
    }//GEN-LAST:event_jDialog1WindowClosing

    private void jDialog1WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowClosed
        att();
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialog1WindowClosed

    private void jConsultaDialogComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jConsultaDialogComponentShown
        this.jCBDia.setModel(Tools.getDiaModel());
        this.jCBAno.setModel(Tools.getAnoModel());
        this.jCBMes.setModel(Tools.getMesModel(0));
        this.jToolBar1.add(this.jCBDia);
        this.jToolBar1.add(this.jCBMes);
        this.jToolBar1.add(this.jCBAno);
    }//GEN-LAST:event_jConsultaDialogComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        att();
    }//GEN-LAST:event_formComponentShown

    /*Configura o jTolbar da janela de edição de acordo com o opção escolhida.
     É adicionado, ou um DatePicker ou um txt*/
    private void jCBSelPropriedadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSelPropriedadeActionPerformed
        String selectedItem = (String) this.jCBSelPropriedade.getSelectedItem();
        if ("data".equalsIgnoreCase((String) jCBSelPropriedade.getSelectedItem())) {
            jToolBar2.removeAll();
            //jToolBar2.repaint();
            this.jCBDia.setModel(Tools.getDiaModel());
            this.jCBAno.setModel(Tools.getAnoModel());
            this.jCBMes.setModel(Tools.getMesModel(0));
            this.jToolBar2.add(jCBDia);
            this.jToolBar2.add(jCBMes);
            this.jToolBar2.add(jCBAno);
        } else if ("especialidade".equalsIgnoreCase(selectedItem)) {
            jToolBar2.removeAll();
            jToolBar2.add(JCBEspecialidade);

        } else {
            jToolBar2.removeAll();
            this.jToolBar2.add(txtEditCliente);
        }
        jToolBar2.validate();
    }//GEN-LAST:event_jCBSelPropriedadeActionPerformed

    //Salva os edits. O ULTIMO A SER CHAMADO
    private void jBSavarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSavarEdicaoActionPerformed
        JTable table = (JTable) this.jPopupMenu.getInvoker(); //Pega a tabela chamada
        String name = table.getName(); //...
        String text = txtEditCliente.getText(); //Novos dados
        String selectedItem = (String) jCBSelPropriedade.getSelectedItem(); //A propriedade a ser trocada
        //Seta pra data caso data tenha sido selecionada
        if ("data".equalsIgnoreCase(selectedItem)) {
            int selectedDia = jCBDia.getSelectedIndex();
            int selectedMes = jCBMes.getSelectedIndex();
            int selectedAno = (int) jCBAno.getSelectedItem();
            text = (selectedDia + 1) + "-" + (selectedMes + 1) + "-" + selectedAno;
        }
        //Especialidade do medico
        if ("especialidade".equalsIgnoreCase(selectedItem)) {
            text = "" + (JCBEspecialidade.getSelectedIndex() + 1);
        }
        int selectedRow = table.getSelectedRow();
        //get cpf
        String valueAt = table.getValueAt(selectedRow, 0).toString();
        //get propriedade
        //String selectedItem = (String) this.jCBSelPropriedade.getSelectedItem();
        if (!"".equals(text)) {
            if (name != null) {
                switch (name) {
                    case "tbCliente":
                        if (_clinica.EditarClienteData(valueAt, selectedItem, text)) {
                            this.txtEditCliente.setText("");
                            Tools.showMessage(1);
                            if (Cliente.uniqueKey.equals(selectedItem)) {
                                this.jDialog1.dispose();;
                                //this.jDialog1WindowClosing(null);
                            }
                        } else {
                            Tools.showMessage(2);
                        }
                        break;
                    case "tbConsulta":
                        if (_clinica.EditarConsulta(valueAt, selectedItem, text)) {
                            this.txtEditCliente.setText("");
                            Tools.showMessage(1);
                            if (Consulta.uniqueKey.equals(selectedItem)) {
                                this.jDialog1.dispose();;
                                //this.jDialog1WindowClosing(null);
                            }
                        } else {
                            Tools.showMessage(2);
                        }
                        break;
                    /*.......................................................................
                     WARNING: NÃO DESTRUA O CÓDIGO ABAIXO
                     Ele não pediu para editar dados do dentista ou funcionario, logo isto 
                     ficara oculto nas sombras.
                     .......................................................................*/
                    /*case "tbDentista":
                     if (_clinica.EditarMedico(valueAt, selectedItem, text)) {
                     this.txtEditCliente.setText("");
                     Tools.showMessage(1);
                     if (Medico.uniqueKey.equals(selectedItem)) {
                     this.jDialog1.dispose();;
                     }
                     } else {
                     Tools.showMessage(2);
                     }
                     break;
                     case "tbFuncionario":
                     if (_clinica.EditarFuncionario(valueAt, selectedItem, text)) {
                     this.txtEditCliente.setText("");
                     Tools.showMessage(1);
                     if (Funcionario.uniqueKey.equals(selectedItem)) {
                     this.jDialog1.dispose();;
                     }
                     } else {
                     Tools.showMessage(2);
                     }
                     break;
                     */
                }
            }
        } else {
            this.jDialog1.dispose();
        }
    }//GEN-LAST:event_jBSavarEdicaoActionPerformed

    /*
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientesPanel;
    private javax.swing.JPanel ConsultasPanel;
    private javax.swing.JPanel GerenciaPanel;
    private javax.swing.JComboBox JCBEspecialidade;
    private javax.swing.JComboBox cbSetRegMed;
    private javax.swing.JButton jBAddDentista;
    private javax.swing.JButton jBSavarEdicao;
    private javax.swing.JButton jBtAddCliente;
    private javax.swing.JButton jBtAddCliente1;
    private javax.swing.JButton jBtAddConsulta;
    private javax.swing.JButton jBtAddNCliente;
    private javax.swing.JButton jBtMarcarConsulta;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jCBAno;
    private javax.swing.JComboBox jCBDia;
    private javax.swing.JComboBox jCBMes;
    private javax.swing.JComboBox jCBSelPropriedade;
    private javax.swing.JDialog jClienteDialog;
    private javax.swing.JDialog jClienteDialog1;
    private javax.swing.JDialog jConsultaDialog;
    private javax.swing.JDialog jDentistaDialog;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JPopupMenu jPopupMenuConsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jbAddDentistadg;
    private javax.swing.JMenuItem popMEditar;
    private javax.swing.JMenuItem popMEditarConsulta;
    private javax.swing.JMenuItem popMExcluir;
    private javax.swing.JMenuItem popMExcluirConsulta;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTable tbConsulta;
    private javax.swing.JTable tbDentista;
    private javax.swing.JTable tbFuncionario;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtCpfCliente1;
    private javax.swing.JTextField txtCpfCliente2;
    private javax.swing.JTextField txtCpfMedico;
    private javax.swing.JTextField txtEditCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeCliente1;
    private javax.swing.JTextField txtNomeMedico;
    private javax.swing.JTextField txtRegistroMedico;
    private javax.swing.JTextField txtTelCliente;
    private javax.swing.JTextField txtTelCliente1;
    // End of variables declaration//GEN-END:variables

}
